version: 1.0.0.{build}

configuration: Release

after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
artifacts:
  - path: src\nuget\titcs.sharepoint
    name: src

deploy:
- provider: NuGet
  server: https://www.myget.org/F/titcs/
  api_key:
    secure: 07c9ebf0-9b2e-4a04-b8ca-098850db17af
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  - stiven@outlook.com
  subject: BoletoNet Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
