version: 1.0.0.{build}

configuration: Release

after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
artifacts:
  - path: src\nuget\titcs.sharepoint
    name: src
    
environment:
  nuget_apy_key:
    secure: gPpssATrDRZaa6fHJn0irm9K1T4LWPuvlDrD23bN1Mbu9VA6TIogGJfoFDN/pxOD

deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: nuget_apy_key.secure
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    
test: off
    
notifications:
- provider: Email
  to:
  - stiven@outlook.com
  subject: TITcs.SharePoint Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
