version: 1.0.0.{build}

configuration: Release

after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
artifacts:
  - path: src\nuget\titcs.sharepoint
    name: src

deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: 002c8896-a070-47fc-92c1-f900c155d407
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    
test: off
    
notifications:
- provider: Email
  to:
  - stiven@outlook.com
  subject: TITcs.SharePoint Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
